package com.bodywithbrain.awsbackend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import javax.validation.constraints.NotEmpty;
import java.time.OffsetDateTime;
import java.util.Set;
import java.util.UUID;


@Data
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@DynamoDBTable(tableName = "Blog_Table")
public class BwbBlog {

    private static final long serialVersionUID = 1;

    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    @DynamoDBHashKey(attributeName = "id")
    private UUID id;

    public Set<String> category;

    @NotEmpty
    public String title;

    @NotEmpty
    public String content;

    public String pictureUrl;

    @DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
    public OffsetDateTime createdOn;

    @NonNull
    @DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
    public OffsetDateTime lastUpdated;

    @NotEmpty
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "usergsi")
    public String createdBy;

}
